[project]
name = 'Language-Learning-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.language-learning-token]
path = 'contracts/language-learning-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.payment-handler]
path = 'contracts/payment-handler.clar'
clarity_version = 2
epoch = 2.5

[contracts.reward-system]
path = 'contracts/reward-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
